repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
        # Run the linter
        - id: ruff
          args: [--fix, --exit-non-zero-on-fix]
        # Run the formatter
        - id: ruff-format

# Uncomment to enable type checking (fix errors incrementally)
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.7.1
#     hooks:
#         - id: mypy
#           additional_dependencies: [types-PyYAML, types-requests]
#           args: [--ignore-missing-imports]
#           exclude: ^experiments/

