- abs_form_points_diff
- abs_momentum_score_diff
- away_avg_goals_against
- away_avg_points
- away_form_avg_goals_conceded
- away_form_avg_goals_scored
- away_form_draws
- away_form_goal_diff
- away_form_goals_conceded
- away_form_goals_scored
- away_form_losses
- away_form_points
- away_goal_diff_ewm5
- away_goals_against_ewm5
- away_goals_conceded_pg_at_home
- away_goals_conceded_pg_away
- away_goals_for_ewm5
- away_goals_pg_at_home
- away_goals_pg_away
- away_momentum_conceded
- away_momentum_goals
- away_momentum_score
- away_points_ewm5
- away_points_pg_at_home
- away_points_pg_away
- form_points_difference
- home_avg_goals_against
- home_avg_goals_for
- home_avg_points
- home_form_avg_goals_conceded
- home_form_avg_goals_scored
- home_form_draws
- home_form_goal_diff
- home_form_goals_conceded
- home_form_goals_scored
- home_form_losses
- home_form_points
- home_goal_diff_ewm5
- home_goals_against_ewm5
- home_goals_conceded_pg_at_home
- home_goals_conceded_pg_away
- home_goals_for_ewm5
- home_goals_pg_at_home
- home_goals_pg_away
- home_momentum_conceded
- home_momentum_goals
- home_momentum_score
- home_points_ewm5
- home_points_pg_away
- home_points_pg_at_home
- momentum_score_difference
- venue_conceded_delta
- venue_goals_delta
- venue_points_delta

