- momentum_score_difference
- home_goal_diff_ewm5
- away_goal_diff_ewm5
- abs_momentum_score_diff # Keep for non-linear effects

# --- Key Ratio Features (High Importance & Logical) ---
- attack_defense_form_ratio_home
- attack_defense_form_ratio_away
- attack_defense_long_ratio_home
- attack_defense_long_ratio_away

# --- Opponent Weakness Features (High Importance & Logical) ---
- away_momentum_conceded # Strong for home goals
- home_momentum_conceded # Strong for away goals
- away_goals_against_ewm5
- home_goals_against_ewm5

# --- Team Strength Features (That Behave Logically) ---
- away_momentum_points # Good for away goals
- home_momentum_goals # Good for home goals
- away_momentum_goals # Good for away goals (negative corr for home goals is logical)
- home_goals_for_ewm5
- away_goals_for_ewm5

# --- Contextual Feature ---
- matchday